// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using musicList2.Database;

namespace musicList2.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("musicList2.Models.ListEntry<string>", b =>
                {
                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("GUID");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
